[2024-02-14T20:02:41.258+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_with_postgres_operator.create_tabledb scheduled__2024-02-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
