[2024-02-14T20:02:41.215+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_with_postgres_operator.create_tabledb manual__2024-02-14T20:02:35.920070+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
